### ISSUE TITLE
Sea lice offspring

### ISSUE THREAD

**Issue by SaraJakubiak** [magicicada/slim#8]
Offspring creation on Cage update.

**Comment by magicicada** [comment]
I've been thinking about this a bit as we mentioned in the meeting on Thursday, and the main thing to know/decide before generating some starter code is how we're storing various genetic states.  I think we probably want two different mechanisms of inheritance at least: the more discrete homozygote/heterozygote setup and an additive almost-continuous model.  Since lice_population is something that belongs to a Cage, my thought is that a genetic distribution for each age group similarly ought to beong to a cage?
